spring.application.name=Client

server.port=8081

eureka.client.service-url.defaltZone=http://localhost:8761/eureka
eureka.client.instace.instace-id=${spring.application.name}:${spring.application.instance_id:${random.value}